spring.application.name: team_pineapple_be

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  config:
    import: application-secret.yml

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    groups-order: desc
    path: /api-docs
  paths-to-match:
    - /**

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  servlet:
    session:
      timeout: 172800